issuemanagement/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'issuemanagement.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('main.urls')),
)

main/urls.py
from django.conf.urls import patterns, include, url
from .views import TicketCreateView, TicketDetailView, TicketUpdateView, UserTicketListView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
        url(r'^$','main.views.home',name="index"),
        url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='login'),
        url(r'^logout/$', 'main.views.logout_view', name='logout'),
        url(r'^tickets/$', UserTicketListView.as_view(), name='ticket_list'),
        url(r'^tickets/new/$', TicketCreateView.as_view(), name='ticket_create'),
        url(r'^tickets/(?P<pk>[0-9]+)/$',TicketDetailView.as_view(), name='ticket_detail'),
        url(r'^tickets/(?P<pk>[0-9]+)/update/$',TicketUpdateView.as_view(), name='ticket_update'),
        url(r'^register/$','main.views.register',name='register'),
    )

urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime

class ClientProfile(models.Model):
    """
    Model to store client profile .
    address,company name, phone number as fields

    """

    user = models.OneToOneField(User, related_name='profile')
    address = models.TextField()
    company_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
   
    def __unicode__(self):
        return u"%s : %s " %(self.user.username, self.company_name)

class Ticket(models.Model):
    """
        Model to store  ticket
    """

    PRIORITY = (
            ('L', 'Low'),
            ('N', 'Normal'),
            ('H', 'High'),
         )

    SLA = {'L':24, 'N':72, 'H':120}
    STATUS = (
            ('N', 'New'),
            ('U', 'Under Investigation'),
            ('R', 'Resolved'),
            ('C', 'Closed'),

         )
    client = models.ForeignKey(User, related_name='ticket')
    name = models.CharField(max_length=200)
    date_time = models.DateTimeField(auto_now_add=True)
    logged_by = models.ForeignKey(User, related_name='logged_ticket')
    assigned_to = models.ForeignKey(User, related_name='assigned_ticket')
    priority = models.CharField(max_length=1, choices=PRIORITY, default=PRIORITY[1][0])
    status = models.CharField(max_length=1,choices=STATUS, default=STATUS[0][0])
    estimated_completion_time = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    resolution = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('ticket_detail', args=[str(self.id)])

    def __unicode__(self):
        return str(self.id) + ':' + self.name + ":" + unicode(self.client) 

main/forms.py
from django import forms 
from main.models import Ticket
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateTicketForm(forms.ModelForm):
    """
        Form for helpdesk executive to create/update a  ticket
    """
    class Meta:
        model = Ticket
        fields = ('client', 'name', 'assigned_to', 'priority', 'description')

class EngineerUpdateTicketForm(forms.ModelForm):
    """
        Form for engineer to create and update ticket
    """

    CHOICES = (
            ('N', 'New'),
            ('U', 'Under Investigation'),
            ('R', 'Resolved'),
         )
    status =  forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Ticket
        fields = ['status', 'description', 'resolution', 'assigned_to']



class SupervisorUpdateTicketForm(forms.ModelForm):
    """
        Form for supervisor to update ticket.

    """

    class Meta:
        model = Ticket
        fields = ['status', 'assigned_to']


class ClientRegistrationForm(UserCreationForm):
    """
    Form for client registration

    """

    address = forms.CharField()
    phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$', error_message = ("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."))

    class Meta:
        model = User
        fields=('first_name','last_name','username','password1','password2','email')

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.models import User, Group
from endless_pagination.views import AjaxListView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.context_processors import csrf
from .models import Ticket, ClientProfile
from .forms import CreateTicketForm, EngineerUpdateTicketForm, SupervisorUpdateTicketForm, ClientRegistrationForm
from django.contrib.auth.models import Group
from datetime import datetime, timedelta
from django.utils import timezone

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}


def register(request):
    """ 
    View for Client registration

    """
    if request.method == 'POST':
        form = ClientRegistrationForm(request.POST)
        if form.is_valid():            
            user = form.save()
            user.groups.add(Group.objects.get(name="Client"))
            client = ClientProfile(user=user,address=form.cleaned_data['address'],phone_number=form.cleaned_data['phone_number'])
            client.save()
            messages.success(request,'Registered successfully and please login')
            return redirect('index')
    args={}
    args.update(csrf(request))
    args['form']=ClientRegistrationForm()

    return render(request,'main/register.html',args)


def home(request):
    """
        View for homepage, with ticket count in context 

    """
    ticket_logged_count = Ticket.objects.all().count()
    ticket_resolved_count = Ticket.objects.filter(status='C').count()
    args = {}
    args['ticket_count'] = ticket_logged_count
    args['ticket_resolved_count'] = ticket_resolved_count

    return render(request,'main/index.html', args)


def logout_view(request):
    """
        View to logout 
    """
    messages.success(request, 'Logged out successfully')
    logout(request)
    return redirect('index')

class TicketCreateView(SuccessMessageMixin, CreateView):
    model = Ticket
    form_class = CreateTicketForm
    success_message = "Ticket was created successfully"


    def get_form(self, form_class):
        form = super(TicketCreateView, self).get_form(form_class)
        form.fields['client'].queryset = User.objects.filter(groups__name='Client')
        form.fields['assigned_to'].queryset = User.objects.filter(groups__name='Engineer')
        return form
    
    def form_valid(self, form):
        form.instance.logged_by = self.request.user
        form.instance.date_time = timezone.now()
        hours_sla = Ticket.SLA[form.instance.priority]
        form.instance.estimated_completion_time = form.instance.date_time + timedelta(hours=hours_sla)
        return super(TicketCreateView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.request.user.groups.filter(name='HelpDesk').exists():
            return super(TicketCreateView, self).dispatch(*args, **kwargs)
        else:
            return redirect('index')



class UserTicketListView(AjaxListView):
    """
        Paginated view to list issues.Issues are listed based on group to which user belongs to and wether he/she
        has permission to view the ticket
    """
    model = Ticket
    context_object_name = "user_ticket_list"
    template_name = "main/user_ticket_list.html"
    page_template = "main/user_ticket_list_page.html"
    paginate_by = 10


    def get_queryset(self):
            if self.request.user.groups.filter(name='HelpDesk').exists():
                ticket_list = Ticket.objects.filter(logged_by = self.request.user)               
            elif self.request.user.groups.filter(name='Engineer').exists():
                ticket_list = Ticket.objects.filter(assigned_to = self.request.user)
            elif self.request.user.groups.filter(name='Client').exists():
                ticket_list = Ticket.objects.filter(client = self.request.user)
            elif self.request.user.groups.filter(name='Supervisor').exists():
                return Ticket.objects.all()
            return ticket_list


class TicketDetailView(DetailView):
    """
        View for displaying Single ticket details
    """
    model = Ticket
    context_object_name = 'ticket'

    def get_context_data(self, **kwargs):
        ticket = self.get_object()
        context = super(TicketDetailView, self).get_context_data(**kwargs)
        context['is_supervisor'] = self.request.user.groups.filter(name='Supervisor').exists()
        timedelta_until_ect = ticket.estimated_completion_time - timezone.now()
        context['time_until_etc'] = timedelta_until_ect.total_seconds() // 3600

        return context


class TicketUpdateView(SuccessMessageMixin, UpdateView):
    """
    View for Updating ticket,it dynamicaly shows form based on user prievelege to update the ticket

    """
    model = Ticket
    context_object_name = 'ticket'
    success_message = "Ticket was updated successfully"

    def get_form_class(self):
        ticket = self.get_object()
        if self.request.user.groups.filter(name='Engineer').exists() and ticket.assigned_to == self.request.user:
            self.template_name = 'main/ticket_engineer_update_form.html'
            return EngineerUpdateTicketForm
        elif self.request.user.groups.filter(name='HelpDesk').exists() and ticket.logged_by == self.request.user:
            self.template_name = 'main/ticket_form.html'
            return CreateTicketForm
        elif self.request.user.groups.filter(name='Supervisor').exists():
            self.template_name='main/ticket_supervisor_update_form.html'
            return SupervisorUpdateTicketForm
        else:
            return None

    def get_form(self, form_class):
        form_class = self.get_form_class()
        form = super(TicketUpdateView, self).get_form(form_class)
        if form_class == EngineerUpdateTicketForm or form_class == SupervisorUpdateTicketForm :
            form.fields['assigned_to'].queryset = User.objects.filter(groups__name='Engineer')

        return form
        

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if not self.get_form_class():
            messages.error(self.request, 'Insufficient Permission to edit the Ticket')
            return redirect('index')
        return super(TicketUpdateView, self).dispatch(*args, **kwargs)
    

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block activelogin %}class="active"{% endblock %}
{% block css %}
 {{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/login.css' %}">
{% endblock %}

{% block head_title %}Login{% endblock %}

{% block content %}
<div class="row" style="height:500px;">
    <div class="column col-md-6 col-md-offset-3" >

        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="login" />
            <input type="hidden" name="next" value="{% url 'index' %}"/>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/ticket_engineer_update_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Ticket Details{% endblock %}
{% block head_extra %}
<style type="text/css">
.head{text-align: center;}
.status{font-size: 150%;}
.ticketno{font-size: 160%; text-align: center;}
.user span{display: inline-block;}
.user{text-align: center; font-size: 150%; padding-top: 8%;}
.priority {padding-top: 10%; font-size: 150%;}
.page-header {text-align: center;}
.desc {padding-top: 4%;}
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>{{ticket.name}} <small>{{ticket.client}}</small></h1>
    </div>
</div>
<form action ="" method="post">
    {% csrf_token %} 
    <div class="row">
        <div class="col-md-6">
            <div class="status">
                Current Status: 
                {{form.status}} 

            </div>
            <div class="priority">
                <div> Priority <span class="glyphicon glyphicon-hand-right"> {{ticket.get_priority_display}}</div>
                {% if ticket.priority == "H" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span class="sr-only">100% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority ==  "N" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority == "L" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h2 class="ticketno">Ticket Number:<span>{{ticket.id}}</span></h2>
                <div class="user">
                    Logged By&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-user">{{ticket.logged_by}}</span><br>
                    Assigned To&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-pencil">{{form.assigned_to}}</span>
                </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 desc">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">About the issue</h3>
                </div>
                <div class="panel-body">
                    {{form.description}}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Resolution of the issue</h3>
                </div>
                <div class="panel-body">
                    {{form.resolution}}
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/ticket_list_page.html
{% load endless %}

<div class="row">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Ticket List</div>
        <!-- Table -->
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Client</th>
                <th>Ticket no</th>
                <th>Status</th>
            </tr>
            {% paginate ticket_list %}

            {% for ticket in ticket_list %}
            <tr class="list_ticket">
                <td><a href="{% url 'ticket_detail' ticket.id %}">{{ticket.name}}</a></td>
                <td>{{ticket.client}}</td>
                <td>{{ticket.id}}</td>
                <td>
                    <span class="label {% if ticket.status == 'N' %}label-default{% elif ticket.status == 'U' %}label-primary{% elif ticket.status == 'R' %}label-info{% elif ticket.status == 'V' %}label-success{% endif %}">{{ticket.get_status_display}}</span>
                </td>
            </tr>
            {% endfor %}

        </table>
        {% show_pages %}
    </div>
</div>

main/templates/main/ticket_supervisor_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Ticket Details{% endblock %}
{% block head_extra %}
<style type="text/css">
.head{text-align: center;}
.status{font-size: 150%;}
.ticketno{font-size: 160%; text-align: center;}
.user span{display: inline-block;}
.user{text-align: center; font-size: 150%; padding-top: 8%;}
.priority {padding-top: 10%; font-size: 150%;}
.page-header {text-align: center;}
.desc {padding-top: 4%;}
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>{{ticket.name}} <small>{{ticket.client}}</small></h1>
    </div>
</div>
<form action ="" method="post">
    {% csrf_token %} 
    <div class="row">
        <div class="col-md-6">
            <div class="status">
                Current Status: 
                {{form.status}} 

            </div>
            <div class="priority">
                <div> Priority <span class="glyphicon glyphicon-hand-right"> {{ticket.get_priority_display}}</div>
                {% if ticket.priority == "H" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span class="sr-only">100% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority ==  "N" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority == "L" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h2 class="ticketno">Ticket Number:<span>{{ticket.id}}</span></h2>
                <div class="user">
                    Logged By&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-user">{{ticket.logged_by}}</span><br>
                    Assigned To&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-pencil">{{ticket.assigned_to}}</span>
                </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 desc">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">About the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.description}}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Resolution of the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.resolution}}
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/ticket_supervisor_update_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Ticket Details{% endblock %}
{% block head_extra %}
<style type="text/css">
.head{text-align: center;}
.status{font-size: 150%;}
.ticketno{font-size: 160%; text-align: center;}
.user span{display: inline-block;}
.user{text-align: center; font-size: 150%; padding-top: 8%;}
.priority {padding-top: 10%; font-size: 150%;}
.page-header {text-align: center;}
.desc {padding-top: 4%;}
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>{{ticket.name}} <small>{{ticket.client}}</small></h1>
    </div>
</div>
<form action ="" method="post">
    {% csrf_token %} 
    <div class="row">
        <div class="col-md-6">
            <div class="status">
                Current Status: 
                {{form.status}} 

            </div>
            <div class="priority">
                <div> Priority <span class="glyphicon glyphicon-hand-right"> {{ticket.get_priority_display}}</div>
                {% if ticket.priority == "H" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span class="sr-only">100% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority ==  "N" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority == "L" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h2 class="ticketno">Ticket Number:<span>{{ticket.id}}</span></h2>
                <div class="user">
                    Logged By&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-user">{{ticket.logged_by}}</span><br>
                    Assigned To&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-pencil">{{form.assigned_to}}</span>
                </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 desc">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">About the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.description}}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Resolution of the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.resolution}}
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/ticket_supervisorform.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Ticket Details{% endblock %}
{% block head_extra %}
<style type="text/css">
.head{text-align: center;}
.status{font-size: 150%;}
.ticketno{font-size: 160%; text-align: center;}
.user span{display: inline-block;}
.user{text-align: center; font-size: 150%; padding-top: 8%;}
.priority {padding-top: 10%; font-size: 150%;}
.page-header {text-align: center;}
.desc {padding-top: 4%;}
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>{{ticket.name}} <small>{{ticket.client}}</small></h1>
    </div>
</div>
<form action ="" method="post">
    {% csrf_token %} 
    <div class="row">
        <div class="col-md-6">
            <div class="status">
                Current Status: 
                {{form.status}} 

            </div>
            <div class="priority">
                <div> Priority <span class="glyphicon glyphicon-hand-right"> {{ticket.get_priority_display}}</div>
                {% if ticket.priority == "H" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span class="sr-only">100% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority ==  "N" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority == "L" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h2 class="ticketno">Ticket Number:<span>{{ticket.id}}</span></h2>
                <div class="user">
                    Logged By&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-user">{{ticket.logged_by}}</span><br>
                    Assigned To&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-pencil">{{ticket.assigned_to}}</span>
                </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 desc">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">About the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.description}}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Resolution of the issue</h3>
                </div>
                <div class="panel-body">
                    {{ticket.resolution}}
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/ticket_update_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Ticket Details{% endblock %}
{% block head_extra %}
<style type="text/css">
.head{text-align: center;}
.status{font-size: 150%;}
.ticketno{font-size: 160%; text-align: center;}
.user span{display: inline-block;}
.user{text-align: center; font-size: 150%; padding-top: 8%;}
.priority {padding-top: 10%; font-size: 150%;}
.page-header {text-align: center;}
.desc {padding-top: 4%;}
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>{{ticket.name}} <small>{{ticket.client}}</small></h1>
    </div>
</div>
<form action ="" method="post">
    {% csrf_token %} 
    <div class="row">
        <div class="col-md-6">
            <div class="status">
                Current Status: 
                {{form.status}} 

            </div>
            <div class="priority">
                <div> Priority <span class="glyphicon glyphicon-hand-right"> {{ticket.get_priority_display}}</div>
                {% if ticket.priority == "H" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span class="sr-only">100% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority ==  "N" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% elif ticket.priority == "L" %}
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h2 class="ticketno">Ticket Number:<span>{{ticket.id}}</span></h2>
                <div class="user">
                    Logged By&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-user">{{ticket.logged_by}}</span><br>
                    Assigned To&nbsp&nbsp&nbsp<span class="glyphicon glyphicon-pencil">{{ticket.assigned_to}}</span>
                </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 desc">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">About the issue</h3>
                </div>
                <div class="panel-body">
                    {{form.description}}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Resolution of the issue</h3>
                </div>
                <div class="panel-body">
                    {{form.resolution}}
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="Update" />
</form>

{% endblock %}

main/templates/main/user_ticket_list_page.html
{% load endless %}

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">Ticket List</div>
        {% if  user_ticket_list %} 
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Client</th>
                <th>Ticket no</th>
                <th>Status</th>
            </tr>
            {% paginate user_ticket_list %}

            {% for ticket in user_ticket_list %}
            <tr class="list_ticket">
                <td><a href="{% url 'ticket_detail' ticket.id %}">{{ticket.name}}</a></td>
                <td>{{ticket.client}}</td>
                <td>{{ticket.id}}</td>
                <td>
                    <span class="label {% if ticket.status == 'N' %}label-default{% elif ticket.status == 'U' %}label-primary{% elif ticket.status == 'R' %}label-info{% elif ticket.status == 'C' %}label-success{% endif %}">{{ticket.get_status_display}}</span>
                </td>
            </tr>
            {% endfor %}

        </table>
        {% show_pages %}

        {% else %}
        <center><h3>No Tickets for you</h3></center>
        {% endif %}

    </div>
</div>